services:
  prefect-server:
    image: prefecthq/prefect:3.4-python3.12
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
      - "3000:3000"
    environment:
      PREFECT_UI_URL: http://localhost:4200
    restart: unless-stopped

  mlflow:
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5050:5000" # Not 5000 because it's already in use in my Mac
    volumes:
      - ./mlruns:/mlruns
      - ./mlartifacts:/mlartifacts
      - ./backend.db:/backend.db
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///backend.db
    restart: unless-stopped
