{
 "title": "Customer churn dashboard",
 "time": { "from": "2025-08-04T14:05:41.286Z", "to": "2025-08-04T14:08:47.184Z" },
 "panels": [
  {
   "title": "Recall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  r.generated_at AS \"time\",\n  (m->>'value')::float AS recall\nFROM evidently_reports r,\n     LATERAL jsonb_array_elements(r.report_json->'metrics') AS m\nWHERE r.report_type = 'performance'\n  AND m->>'metric_id' = 'Recall(conf_matrix=True,pr_curve=False,pr_table=False)'\nORDER BY r.generated_at"
    }
   ]
  },
  {
   "title": "Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  r.generated_at AS \"time\",\n  (m->>'value')::float AS accuracy\nFROM evidently_reports r,\n     LATERAL jsonb_array_elements(r.report_json->'metrics') AS m\nWHERE r.report_type = 'performance'\n  AND m->>'metric_id' = 'Accuracy()'\nORDER BY r.generated_at\n"
    }
   ]
  },
  {
   "title": "Churned users",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE WHEN churn THEN 'Churned' ELSE 'Not churned' END AS churn_status,\n  COUNT(*) AS user_count\nFROM users\nGROUP BY churn_status\nORDER BY churn_status;\n"
    }
   ]
  },
  {
   "title": "Drift in prediction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  r.generated_at AS \"time\",\n  (m->>'value')::float AS value_drift\nFROM evidently_reports r,\n     LATERAL jsonb_array_elements(r.report_json->'metrics') AS m\nWHERE r.report_type = 'drift'\n  AND m->>'metric_id' = 'ValueDrift(column=prediction)'\nORDER BY r.generated_at"
    }
   ]
  },
  {
   "title": "Predictions by month",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_TRUNC('month', predicted_at) AS month,\n  COUNT(*) AS prediction_count\nFROM predictions_history\nGROUP BY month\nORDER BY month;\n"
    }
   ]
  },
  {
   "title": "Data missing count",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  r.generated_at AS \"time\",\n  ((m->'value'->>'count')::float) AS missing_values\nFROM evidently_reports r,\n     LATERAL jsonb_array_elements(r.report_json->'metrics') AS m\nWHERE r.report_type = 'quality'\n  AND m->>'metric_id' = 'DatasetMissingValueCount()'\nORDER BY r.generated_at\n"
    }
   ]
  }
 ]
}